SECRET_KEY_BASE: "thisisasupersecret"
DEVISE_PEPPER: 'f3998fdf09b95a8ca3e895d0dafaa78e410eed53cc02341d25f521071a43a9d9d3d9efda73488e9f8b9be7847638482c5d94a86dd1d549dbe1bd9a8e9d957a12'
WUFOO_HANDSHAKE_KEY: ""
GIBBON_API_KEY: ""
TWILIO_API_SID: ""
TWILIO_API_TOKEN: ""
TWILIO_ACCOUNT_SID: ""
TWILIO_AUTH_TOKEN: ""
TWILIO_NUMBER: ""
WUFOO_ACCOUNT: ""
WUFOO_API: ""
WUFOO_SIGNUP_FORM: ""
WUFOO_HANDSHAKE_KEY: ""
MAILCHIMP_API_KEY: ""
MAILCHIMP_LIST_ID: ""
PRODUCTION_SERVER: "example.com"
PRODUCTION_BRANCH: "master"
STAGING_SERVER: "staging.example.com"
STAGING_BRANCH: "devlopment"
GIT_REPOSITORY: "git@github.com:example/example.git"
TIME_ZONE: "Central Time (US & Canada)"
MAILER_SENDER: "hello@example.com"